spring:
  datasource:
    url: jdbc:h2:file:~/data/insurancedb
    username: hditest
    password: hditest
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update